# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/soc/soc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc || ORIG_REF_NAME==soc} -quiet] -quiet

# IP: bd/soc/ip/soc_zynq_ultra_ps_e_0_0/soc_zynq_ultra_ps_e_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==soc_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_clk_wiz_0_0 || ORIG_REF_NAME==soc_clk_wiz_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_proc_sys_reset_0_0/soc_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_proc_sys_reset_0_0 || ORIG_REF_NAME==soc_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_proc_sys_reset_0_1 || ORIG_REF_NAME==soc_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/soc/ip/soc_proc_sys_reset_0_2/soc_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_proc_sys_reset_0_2 || ORIG_REF_NAME==soc_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/soc/ip/soc_proc_sys_reset_0_3/soc_proc_sys_reset_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_proc_sys_reset_0_3 || ORIG_REF_NAME==soc_proc_sys_reset_0_3} -quiet] -quiet

# IP: bd/soc/ip/soc_proc_sys_reset_0_4/soc_proc_sys_reset_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_proc_sys_reset_0_4 || ORIG_REF_NAME==soc_proc_sys_reset_0_4} -quiet] -quiet

# IP: bd/soc/ip/soc_xlconcat_0_0/soc_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==soc_xlconcat_0_0 || ORIG_REF_NAME==soc_xlconcat_0_0} -quiet] -quiet

# XDC: bd/soc/soc_ooc.xdc
