# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 4
create_project -in_memory -part xczu3eg-sbva484-1-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.cache/wt [current_project]
set_property parent.project_path /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:ultra96v1:part0:1.2 [current_project]
set_property ip_output_repo /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/hdl/soc_wrapper.v
add_files /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/soc.bd
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_zynq_ultra_ps_e_0_0/soc_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_zynq_ultra_ps_e_0_0/soc_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_0/soc_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_0/soc_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_0/soc_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_2/soc_proc_sys_reset_0_2_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_2/soc_proc_sys_reset_0_2.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_2/soc_proc_sys_reset_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_3/soc_proc_sys_reset_0_3_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_3/soc_proc_sys_reset_0_3.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_3/soc_proc_sys_reset_0_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_4/soc_proc_sys_reset_0_4_board.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_4/soc_proc_sys_reset_0_4.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_4/soc_proc_sys_reset_0_4_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/soc_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top soc_wrapper -part xczu3eg-sbva484-1-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_wrapper_utilization_synth.rpt -pb soc_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
