# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xci
# IP: The module: 'soc_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xci
# IP: The module: 'soc_proc_sys_reset_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_proc_sys_reset_0_1/soc_proc_sys_reset_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'soc_proc_sys_reset_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
