set_property PACKAGE_PIN N2 [get_ports mipi_phy_if_0_clk_p]
set_property PACKAGE_PIN P1 [get_ports mipi_phy_if_0_clk_n]
set_property PACKAGE_PIN N5 [get_ports {mipi_phy_if_0_data_p[0]}]
set_property PACKAGE_PIN N4 [get_ports {mipi_phy_if_0_data_n[0]}]
set_property PACKAGE_PIN M2 [get_ports {mipi_phy_if_0_data_p[1]}]
set_property PACKAGE_PIN M1 [get_ports {mipi_phy_if_0_data_n[1]}]
set_property PACKAGE_PIN M5 [get_ports {mipi_phy_if_0_data_p[2]}]
set_property PACKAGE_PIN M4 [get_ports {mipi_phy_if_0_data_n[2]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
