set_property SRC_FILE_INFO {cfile:/home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xdc rfile:../../../../../ultra96_platform.srcs/sources_1/bd/soc/ip/soc_clk_wiz_0_0/soc_clk_wiz_0_0.xdc id:1 order:EARLY scoped_inst:inst} [current_design]
set_property SRC_FILE_INFO {cfile:/home/rouholla/myData/zynq_projects/Vitis_Projects/ultra96_platform/ultra96_platform.runs/soc_clk_wiz_0_0_synth_1/dont_touch.xdc rfile:../../../dont_touch.xdc id:2} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk_in1 [get_ports clk_in1]
current_instance inst
set_property src_info {type:SCOPED_XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property PHASESHIFT_MODE LATENCY [get_cells mmcme4_adv_inst]
current_instance
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clkfbout_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKFBOUT]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out1_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 1 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKOUT0]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out2_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 2 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKOUT1]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out3_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 3 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKOUT2]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out4_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 4 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKOUT3]
set_property src_info {type:PI file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_out5_soc_clk_wiz_0_0 -source [get_pins inst/mmcme4_adv_inst/CLKIN1] -multiply_by 6 -add -master_clock [get_clocks clk_in1] [get_pins inst/mmcme4_adv_inst/CLKOUT4]
set_property src_info {type:XDC file:2 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property DONT_TOUCH true [get_cells inst]
